import {
  event1,
  event2,
  event3,
  event4,
  event5,
  event6,
  event7,
  event8,
  event9,
  event10,
} from "@/public/assets";

export const events = [
  {
    event_id: 10,
    title: "Event 10",
    banner: event10,
    description:
      "Animation guinness ce samedi 31 avec ng bling et fetty ndoss . Entrée gratuite 🔥🔥🔥",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/10",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 23,
      total_reads: 10,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 9,
    title: "Event 9",
    banner: event9,
    description:
      "Demain il y'a le traditionnel culte des immatures avec Mr WilS .Dj Khaled Le Goûteux  , Deejay Dann  et  Djkelch Mix au mix 🔥🔥 Mais aujourd'hui il y'a SATDAY d'abord🥰",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/9",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 8,
    title: "Event 8",
    banner: event8,
    description:
      "Si vous ne gagnez pas ,on ferme le portail là, personne ne sort ! On remet les organes vendredi 💚💛💙",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/8",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 7,
    title: "Event 7",
    banner: event7,
    description:
      "L'équipe choc vous donne rendez-vous demain dimanche 29 septembre pour une ambiance exceptionnelle. Dj Khaled Le Goûteux  , Deejay Dann  et Djkelch Mix au mix . Mr WilS à l'animation",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/7",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 6,
    title: "Event 6",
    banner: event6,
    description:
      "Le week-end commence vendredi. Votre programme du vendredi et du samedi est connu ,c'est le FRI-SATDAY 🔥🔥🔥",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/6",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },

  {
    event_id: 5,
    title: "Event 5",
    banner: event5,
    description:
      "C'est mon anniversaire, mais c'est moi qui vous offre ce magnifique cadeau 🫶🏻🫶🏻 Roseline LAYO  sera en prestation ce dimanche 8 septembre 2024 🥵🥵Il y'aura également d'autres artistes et un énorme gâteau à se partager 🥰🥰Venez nombreux ⛔️Droit d'entrée : 2000 fcfa",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 2000,
    isFree: false,
    url: "/event/6",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Patson",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 4,
    title: "Event 4",
    banner: event4,
    description:
      "Encore plus de formules pour votre bonheur 🥰🥰Le week-end commence demain avec le  FRI-SATDAY 🔥🔥🔥",
    location: "Charbonnage",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/6",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 3,
    title: "Event 3",
    banner: event3,
    description:
      "Le Real Madrid C.F.  reçoit le FC Barcelona  ce samedi 26 octobre dès 20h 00 min. Venez vivre ce match dans une ambiance à couper le souffle ,comme si vous étiez au stade 🔥🔥𝙑𝙚𝙣𝙚𝙯 𝙩𝙤̂𝙩, 𝙡𝙚𝙨 𝙥𝙡𝙖𝙘𝙚𝙨 𝙨𝙤𝙣𝙩 𝙡𝙞𝙢𝙞𝙩𝙚́𝙚𝙨. ☎️: 074 09 87 81 𝘋𝑟𝘦𝑠𝘴 𝘤𝑜𝘥𝑒 : 𝑚𝘢𝑖𝘭𝑙𝘰𝑡 𝑑𝘦 𝘧𝑜𝘰𝑡𝘣𝑎𝘭𝑙",
    location: "Owendo",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/6",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 2,
    title: "Event 2",
    banner: event2,
    description:
      "Vous connaissez le concept 🥰🥰on est en mode formules vendredi et samedi: c'est le FRI-SATDAY 🔥🔥🔥",
    location: "Akanda",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 0,
    isFree: true,
    url: "/event/6",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Jerry",
    activity: {
      total_likes: 10,
      total_reads: 13,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
  {
    event_id: 1,
    title: "Event 1",
    banner: event1,
    description:
      "Roi de l'illusion, il est venu nous faire une visite surprise la dernière fois 😅Cette fois ci nous vous annonçons officiellement que General ithachi sera avec nous ce dimanche 25 août pour un show mémorable. Droit d'entrée : KOLO  🍬 Mr WilS à l'animation,  Dj Khaled Le Goûteux  , Deejay Dann  et Djkelch Mix au mix .",
    location: "Alibandeng",
    startDateTime: new Date(2022, 11, 10, 10, 0),
    endDateTime: new Date(2022, 11, 10, 12, 0),
    price: 2000,
    isFree: false,
    url: "/event/6",
    category: "ShowCase",
    content: [],
    tags: [],
    author: "Brandon",
    activity: {
      total_likes: 25,
      total_reads: 12,
    },
    draft: false,
    publishedAt: new Date(2022, 10, 31),
    updatedAt: new Date(2022, 10, 31),
  },
];
